export const DAILY_WORDS = [
  "abundance",
  "accurate",
  "achieve",
  "adapt",
  "admire",
  "adversity",
  "ambitious",
  "anticipate",
  "appreciate",
  "approach",
  "appropriate",
  "assessment",
  "assume",
  "available",
  "aware",
  "benefit",
  "brilliant",
  "capacity",
  "challenge",
  "clarify",
  "coherent",
  "collaborate",
  "commitment",
  "community",
  "compassion",
  "competent",
  "comprehensive",
  "confidence",
  "confront",
  "considerate",
  "consistent",
  "contribute",
  "convince",
  "courage",
  "crucial",
  "curiosity",
  "dedicate",
  "deliberate",
  "demonstrate",
  "determined",
  "diligent",
  "discipline",
  "diverse",
  "effective",
  "efficient",
  "elaborate",
  "embrace",
  "encourage",
  "endeavor",
  "enthusiasm",
  "evaluate",
  "expand",
  "explore",
  "flexible",
  "focus",
  "fortunate",
  "genuine",
  "grateful",
  "harmony",
  "hesitate",
  "humility",
  "identify",
  "immerse",
  "implement",
  "improve",
  "inspire",
  "integrate",
  "intention",
  "interpret",
  "invest",
  "invaluable",
  "involved",
  "justify",
  "knowledge",
  "maintain",
  "mature",
  "meaningful",
  "mindset",
  "motivate",
  "negotiate",
  "notable",
  "objective",
  "optimize",
  "outcome",
  "overcome",
  "participate",
  "patient",
  "perceive",
  "persistent",
  "perspective",
  "phenomenon",
  "positive",
  "potential",
  "practical",
  "precise",
  "prepare",
  "prioritize",
  "profound",
  "pursue",
  "resilience",
  "resourceful",
  "significant",
  "sophisticated",
  "thorough",
  "thrive",
  "transform",
  "transparent",
  "unique",
  "versatile",
  "vulnerable",
];

export type PhrasalVerbFallback = {
  phrase: string;
  definition: string;
  example: string;
};

export const DAILY_PHRASAL_VERBS: PhrasalVerbFallback[] = [
  {
    phrase: "give up",
    definition: "to stop trying to do something",
    example: "She gave up smoking last year.",
  },
  {
    phrase: "look up",
    definition: "to search for information about something",
    example: "I looked up the word in the dictionary.",
  },
  {
    phrase: "turn on",
    definition: "to make a device start working",
    example: "Please turn on the lights.",
  },
  {
    phrase: "put off",
    definition: "to delay or postpone something",
    example: "They put off the meeting until Friday.",
  },
  {
    phrase: "take off",
    definition: "to start flying or to suddenly become successful",
    example: "The plane took off on time.",
  },
  {
    phrase: "set up",
    definition: "to arrange, establish, or prepare something",
    example: "They set up a new company last summer.",
  },
  {
    phrase: "go on",
    definition: "to continue or happen",
    example: "Please go on with your story.",
  },
  {
    phrase: "run out",
    definition: "to be completely used up",
    example: "We ran out of milk this morning.",
  },
  {
    phrase: "break down",
    definition: "to stop working or fail",
    example: "The car broke down on the highway.",
  },
  {
    phrase: "carry on",
    definition: "to continue doing something",
    example: "Carry on with your work.",
  },
  {
    phrase: "come across",
    definition: "to find something by chance",
    example: "I came across an old photo yesterday.",
  },
  {
    phrase: "figure out",
    definition: "to understand or solve something",
    example: "I can't figure out this puzzle.",
  },
  {
    phrase: "get along",
    definition: "to have a good relationship with someone",
    example: "They get along well together.",
  },
  {
    phrase: "bring up",
    definition: "to raise a child or mention a topic",
    example: "She was brought up in Tehran.",
  },
  {
    phrase: "call off",
    definition: "to cancel something",
    example: "The match was called off due to rain.",
  },
  {
    phrase: "check in",
    definition: "to register at a hotel or airport",
    example: "We checked in at noon.",
  },
  {
    phrase: "cut down",
    definition: "to reduce the amount of something",
    example: "You should cut down on sugar.",
  },
  {
    phrase: "drop off",
    definition: "to deliver someone or something to a place",
    example: "I'll drop you off at the station.",
  },
  {
    phrase: "find out",
    definition: "to discover a fact or information",
    example: "I found out the truth at last.",
  },
  {
    phrase: "get over",
    definition: "to recover from an illness or difficult experience",
    example: "He is getting over the flu.",
  },
  {
    phrase: "give in",
    definition: "to finally agree or stop resisting",
    example: "Don't give in to pressure.",
  },
  {
    phrase: "hang out",
    definition: "to spend time relaxing with people",
    example: "We hang out every weekend.",
  },
  {
    phrase: "hold on",
    definition: "to wait for a short time",
    example: "Hold on a moment, please.",
  },
  {
    phrase: "keep up",
    definition: "to continue at the same speed or level",
    example: "Try to keep up with the class.",
  },
  {
    phrase: "look after",
    definition: "to take care of someone or something",
    example: "She looks after her little brother.",
  },
  {
    phrase: "look forward to",
    definition: "to feel excited about something in the future",
    example: "I look forward to seeing you.",
  },
  {
    phrase: "make up",
    definition: "to invent a story or to end an argument",
    example: "He made up an excuse for being late.",
  },
  {
    phrase: "pass out",
    definition: "to suddenly become unconscious",
    example: "He passed out from the heat.",
  },
  {
    phrase: "pick up",
    definition: "to collect something or to learn something quickly",
    example: "I picked up some Spanish while traveling.",
  },
  {
    phrase: "point out",
    definition: "to mention or draw attention to something",
    example: "She pointed out my mistake.",
  },
  {
    phrase: "put on",
    definition: "to wear something",
    example: "Put on your coat, it's cold today.",
  },
  {
    phrase: "put up with",
    definition: "to tolerate something annoying",
    example: "I can't put up with this noise anymore.",
  },
  {
    phrase: "settle down",
    definition: "to become calm or to start living in one place",
    example: "They settled down in a small town.",
  },
  {
    phrase: "show up",
    definition: "to arrive at a place",
    example: "He showed up late again.",
  },
  {
    phrase: "take after",
    definition: "to resemble a parent or relative",
    example: "She takes after her mother.",
  },
  {
    phrase: "take over",
    definition: "to gain control of something",
    example: "The new manager took over the team.",
  },
  {
    phrase: "think over",
    definition: "to consider something carefully",
    example: "Think it over before you decide.",
  },
  {
    phrase: "turn down",
    definition: "to reject an offer or request",
    example: "He turned down the job offer.",
  },
  {
    phrase: "turn up",
    definition: "to increase volume or to appear unexpectedly",
    example: "Turn up the volume, please.",
  },
  {
    phrase: "work out",
    definition: "to exercise or to solve a problem",
    example: "I work out three times a week.",
  },
  {
    phrase: "wear out",
    definition: "to become unusable from use or to become exhausted",
    example: "These shoes are worn out.",
  },
  {
    phrase: "watch out",
    definition: "to be careful or alert",
    example: "Watch out for the steps.",
  },
  {
    phrase: "calm down",
    definition: "to become relaxed and less upset",
    example: "Calm down and take a deep breath.",
  },
  {
    phrase: "wake up",
    definition: "to stop sleeping",
    example: "I wake up at 7 every day.",
  },
  {
    phrase: "stand out",
    definition: "to be very noticeable",
    example: "Her talent stood out at the audition.",
  },
  {
    phrase: "get rid of",
    definition: "to remove or eliminate something",
    example: "We got rid of the old furniture.",
  },
  {
    phrase: "meet up",
    definition: "to meet someone by arrangement",
    example: "Let's meet up for coffee tomorrow.",
  },
  {
    phrase: "come up with",
    definition: "to think of an idea or plan",
    example: "She came up with a brilliant plan.",
  },
  {
    phrase: "back up",
    definition: "to support someone or to copy files for safety",
    example: "Back up your files regularly.",
  },
  {
    phrase: "count on",
    definition: "to rely on someone or something",
    example: "You can count on me.",
  },
];