export const PANEL_TOPICS: string[] = [
  "Should students be allowed to use phones in class?",
  "Is remote work better than working from an office?",
  "What makes someone a good friend?",
  "Should fast food be banned in schools?",
  "Is social media making us more lonely?",
  "What is the best age to start learning a new language?",
  "Should exams be replaced with continuous assessment?",
  "Is money the most important thing for a happy life?",
  "Should zoos be closed forever?",
  "What is the best way to spend a weekend?",
  "Is it better to live in a big city or a small town?",
  "Should homework be abolished?",
  "Are video games a waste of time?",
  "What makes a city feel like home?",
  "Should recycling be made compulsory?",
  "Is breakfast really the most important meal of the day?",
  "Should people be paid to donate blood?",
  "What is the secret to a long and healthy life?",
  "Is online dating better than meeting people in person?",
  "Should all books be available for free online?",
  "What is the most useful skill to learn in 2026?",
  "Should kids have their own smartphones?",
  "Is it better to travel alone or with a group?",
  "Should plastic bags be banned everywhere?",
  "What does success really mean to you?",
  "Is artificial intelligence a friend or a threat?",
  "Should school uniforms be compulsory?",
  "What is the best way to learn from mistakes?",
  "Is it okay to keep pets in apartments?",
  "Should museums and galleries be free to visit?",
  "What makes a book better than its movie?",
  "Is it better to save money or enjoy it now?",
  "Should driving tests be much harder?",
  "What is the most important invention of all time?",
  "Is it better to be the oldest or the youngest sibling?",
  "Should everyone be required to do military service?",
  "What is the best way to start a conversation with a stranger?",
  "Is it better to work for yourself or for a company?",
  "Should advertising be banned for children?",
  "What makes someone a great teacher?",
  "Is it better to live alone or with roommates?",
  "Should public transportation be free?",
  "What is the biggest challenge your generation faces?",
  "Is it better to rent or buy a home?",
  "Should junk food be taxed like cigarettes?",
  "What is the most beautiful place you have ever seen?",
  "Is it better to be good at many things or great at one?",
  "Should voting be compulsory?",
  "What is the best way to reduce plastic waste?",
  "Is it better to speak two languages or one perfectly?",
  "Should companies be allowed to track their employees?",
  "What is the most underrated career in the world?",
  "Is it better to be famous or respected?",
  "Should animals be used for scientific experiments?",
  "What is the best advice you have ever received?",
  "Is it better to graduate early or take your time?",
  "Should everyone learn how to cook before leaving school?",
  "What makes a movie a masterpiece?",
  "Is it better to be the first or the last to arrive at a party?",
  "Should people work fewer hours per week?",
  "What is the best way to deal with stress?",
  "Is it better to live near your family or far away?",
  "Should election campaigns be funded only by the government?",
  "What is the most valuable thing you own that is not money?",
  "Is it better to read the news or to ignore it?",
  "Should children be allowed to choose their own hobbies?",
  "What is the best way to make new friends as an adult?",
  "Is it better to be an introvert or an extrovert?",
  "Should people be allowed to sell their organs?",
  "What is the most important subject in school?",
  "Is it better to live a long simple life or a short exciting one?",
  "Should sports stars be role models?",
  "What is the best way to spend a rainy day?",
  "Is it better to give gifts or experiences?",
  "Should cities be designed for cars or for people?",
  "What is the most underrated food in your country?",
  "Is it better to be a generalist or a specialist?",
  "Should people get paid for housework?",
  "What is the best thing about being a child?",
  "Is it better to live in the present or plan for the future?",
  "Should cars be banned from city centers?",
  "What is the best way to learn a new language quickly?",
  "Is it better to have a few close friends or many acquaintances?",
  "Should people retire at a fixed age?",
  "What is the most important meal to share with family?",
  "Is it better to travel far or to explore your own country?",
  "Should everyone be able to access the internet for free?",
  "What is the best way to apologize?",
  "Is it better to be creative or logical?",
  "Should beauty contests be abolished?",
  "What is the most important holiday in your culture?",
  "Is it better to write letters or send messages?",
  "Should space exploration be a priority?",
  "What is the best way to stay motivated?",
  "Is it better to be an only child or have siblings?",
  "Should music and art be required subjects in school?",
  "What is the most important quality in a leader?",
  "Is it better to finish what you start or move on?",
  "Should people be allowed to work until they are 80?",
  "What is the best way to say thank you?",
  "Is it better to be realistic or optimistic?",
  "Should every child learn to swim?",
];

const SATURDAY_EPOCH_MS = Date.UTC(2026, 0, 3);

export function weekIndexFor(date: Date = new Date()): number {
  const dayMs = 24 * 60 * 60 * 1000;
  const todayUtc = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  return Math.floor((todayUtc - SATURDAY_EPOCH_MS) / (7 * dayMs));
}

export function getPanelTopic(date: Date = new Date()): string {
  const index = weekIndexFor(date) % PANEL_TOPICS.length;
  return PANEL_TOPICS[((index % PANEL_TOPICS.length) + PANEL_TOPICS.length) % PANEL_TOPICS.length];
}
